### PR TITLE
Optionally enable Spinnaker feature flags

### PR DESCRIPTION
**Pull request by dpujadas**
Enable a list of feature flags as explained in the docs (https://www.spinnaker.io/reference/halyard/commands/#hal-config-features-edit)

### CODE REVIEW

**Comment by viglesiasce** [comment]
@dpujadas can you take a quick look at what I added recently here:
https://github.com/viglesiasce/charts/blob/spin-v1.0.0/stable/spinnaker/README.md#automated

I'm trying to avoid having to add a values flag for all of the supported customizations. WDYT?

**Comment by dpujadas** [comment]
I think that your approach with automated commands is well suited for:

- hal commands with lots of parameters / options (as you said, it would be hard to have values for ALL of the supported customizations)
- future hal features not supported by a specific chart version

In my opinion, enabling feature flags is easier to handle with a yaml list. Do you agree?

**Comment by viglesiasce** [comment]
Hey @dpujadas!

I'm partially convinced although a lot of those features require significant out of band configuration to be useful (artifacts, chaos, and mine-canary). That said I think we should enable jobs by default for the chart.

Can you make the change to default to jobs being enabled?

**Comment by dpujadas** [comment]
'Jobs' enabled by default

**Comment by viglesiasce** [comment]
Thanks @dpujadas!

**Pull request merged**
